### ISSUE TITLE
Hunger Calculations fail after eating large amounts of food items

### ISSUE THREAD

**Issue by Delfite** [OpenSauce04/sauces-food-rework#1]
**Environment**
Minecraft Version: 1.12.2
Forge Version: 14.23.5.2860
Mod Version 1.0.3

**Describe the bug**
After eating a large number of food items (independent of how much hunger each item restores) you will eventually come down to 1 hunger point on your hunger bar, but unlike all the other times you've reached 1 hunger point you'll stop regenerating HP completely and won't be able to eat any food to recover any lost HP.

**Log File**
Latest.log: https://mclo.gs/RxUhgcj

**Screenshots**
![2022-12-12_21 14 59](https://user-images.githubusercontent.com/23504262/207211421-56c4f855-0e32-46fa-b86f-35419e27aa21.png)
I'm unable to eat the persimmon in my main hand despite clearly being hurt and playing on Hard difficulty with 1 hunger point remaining

**Final Notes**
In addition to fixing this bug, add a config option that allows the player to eat food even if they have hunger left, removing the ability to eat until you're completely out of food defeats the whole purpose of the hunger bar in the first place. Even versions of Minecraft that used food to directly restore health let you use food items even if you weren't at zero health (because obviously that would defeat the entire purpose of having a health bar in the first place now wouldn't it?) Restarting the world doesn't fix this issue.

**Comment by Delfite** [comment]
@OpenSauce04 Please look into this issue. I want to use your mod but as long as this bug exists I simply can't until it gets fixed.

**Comment by OpenSauce04** [comment]
Hey, sorry I missed your report until now! I'm busy today, but I will investigate your report tomorrow
Thanks for bringing this to my attention, and I will look into adding the config option :)

**Comment by OpenSauce04** [comment]
I couldn't recreate this issue, I sat in a creative world with poison and stacks of food for a long time and it just didn't happen. I am however going to add the config option to allow you to always eat food, and I am also going to adjust how the regeneration works to no longer "slow down" when you have a small amount of hunger; This should stop the issue you described from happening.
I hope this helps you out

**Comment by OpenSauce04** [comment]
@Delfite 1.0.4 has released, read the patch notes for more detailed info

**Comment by OpenSauce04** [comment]
@Delfite Update 1.1.0 has been released; Please check the patch notes for more detailed information

**Comment by Delfite** [comment]
Thanks a bunch for this patch. Even if it's just a config option it's still massively helpful to have now. Though don't think I'm done with you yet on suggestions...
